#!/bin/bash

# read-secret: input a secret passphare

if read -t 10 -sp "Enter secret passphrase > " password; then

  # -e to interpret backslashes
  echo -e "\nSecret passphrase = '$password'"
else
  echo -e "\nInput timed out" >&2
  exit 1
fi
