#!/bin/bash

# read-menu: display system information

# Display the menu and the options to select
cat <<-_EOF_
Please Select:
1. Display System Information
2. Display Disk Space
3. Display Home Space Utilization
0. Quit

_EOF_

# Read the input from the user and let reply to hold the answer
read -p "Enter selection [0-3] > "

# quit
if [[ "$REPLY" -eq 0 ]]; then
  echo "Program terminated."
  exit
fi

# system information
if [[ "$REPLY" -eq 1 ]]; then
  cat <<-_EOF_
  Hostname: $HOSTNAME
  $(uptime)
_EOF_
fi

# disk space
if [[ "$REPLY" -eq 2 ]]; then
  echo "$(df -h)"
  exit
fi
